apiVersion: v2
name: caipe-ui-mongodb
description: MongoDB database for CAIPE UI persistence
type: application
version: 1.0.0-outshift.20260905.3
appVersion: "1.0.0-outshift.20260905.3"
dependencies: []
