apiVersion: v2
name: slack-bot
description: Slack bot integration for AI Platform Engineering using the CAIPE UI BFF
version: 1.0.0-outshift.20260905.8
appVersion: 1.0.0-outshift.20260905.8
type: application
dependencies: []
