apiVersion: v2
name: webex-bot
description: Webex bot integration for AI Platform Engineering using the CAIPE UI BFF
version: 1.0.0-outshift.20260905.6
appVersion: 1.0.0-outshift.20260905.6
type: application
dependencies: []
