apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-init-scripts
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  reconcile-user-profile.sh: |-
    {{- .Files.Get "scripts/reconcile-user-profile.sh" | nindent 4 }}
  mcp-dcr.sh: |-
    {{- .Files.Get "scripts/mcp-dcr.sh" | nindent 4 }}
  init-token-exchange.sh: |-
    {{- .Files.Get "scripts/init-token-exchange.sh" | nindent 4 }}
  init-idp.sh: |-
    {{- .Files.Get "scripts/init-idp.sh" | nindent 4 }}
